<a href="https://colab.research.google.com/github/dragos000/Pytorch-Tutorial/blob/main/pytorch_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import numpy as np

In [4]:
## Python Lists
my_list = [1,2,3,4]
my_list

[1, 2, 3, 4]

In [6]:
### Numpy Arrays
np1 = np.random.rand(3,4)
np1

array([[0.01820901, 0.22996074, 0.8701962 , 0.73370355],
       [0.4380219 , 0.52297514, 0.05939882, 0.2758449 ],
       [0.55497641, 0.95128582, 0.73873837, 0.68818274]])

In [8]:
np1.dtype

dtype('float64')

In [10]:
## Tensor
tensor_2d = torch.rand(3,4)
tensor_2d

tensor([[0.7404, 0.0478, 0.3121, 0.4906],
        [0.5476, 0.4846, 0.0202, 0.9699],
        [0.7199, 0.1014, 0.8302, 0.6234]])

In [11]:
tensor_2d.dtype

torch.float32

In [12]:
## Create tensor from np array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.0182, 0.2300, 0.8702, 0.7337],
        [0.4380, 0.5230, 0.0594, 0.2758],
        [0.5550, 0.9513, 0.7387, 0.6882]], dtype=torch.float64)

### **Video #3**

In [14]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# Reshape & View
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [19]:
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
my_torch2 = my_torch2.reshape(2,-1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [27]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
my_torch4 = my_torch3.view(5,2)
my_torch4

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [30]:
# with reshape and view, they will update
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [32]:
my_torch5[1]=4141
my_torch5

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [33]:
my_torch6

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [34]:
# Slices
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
# Grab one item; it is still a tensor
my_torch7[7]

tensor(7)

In [38]:
# Grab a slice
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [39]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [40]:
# Keep the original shape, return a column
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

### **Video #4**