<a href="https://colab.research.google.com/github/dragos000/Pytorch-Tutorial/blob/main/pytorch_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import numpy as np

In [4]:
## Python Lists
my_list = [1,2,3,4]
my_list

[1, 2, 3, 4]

In [5]:
### Numpy Arrays
np1 = np.random.rand(3,4)
np1

array([[0.97739544, 0.91981744, 0.29776286, 0.17418945],
       [0.54352464, 0.68724118, 0.1348476 , 0.80135234],
       [0.05601904, 0.32632114, 0.07029123, 0.93354033]])

In [6]:
np1.dtype

dtype('float64')

In [7]:
## Tensor
tensor_2d = torch.rand(3,4)
tensor_2d

tensor([[0.8798, 0.2894, 0.8295, 0.1793],
        [0.4433, 0.1794, 0.5393, 0.2190],
        [0.8890, 0.0032, 0.5200, 0.4344]])

In [8]:
tensor_2d.dtype

torch.float32

In [9]:
## Create tensor from np array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.9774, 0.9198, 0.2978, 0.1742],
        [0.5435, 0.6872, 0.1348, 0.8014],
        [0.0560, 0.3263, 0.0703, 0.9335]], dtype=torch.float64)

### **Video #3**

In [10]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# Reshape & View
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [12]:
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
my_torch2 = my_torch2.reshape(2,-1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [14]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
my_torch4 = my_torch3.view(5,2)
my_torch4

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [16]:
# with reshape and view, they will update
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [18]:
my_torch5[1]=4141
my_torch5

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [19]:
my_torch6

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [20]:
# Slices
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
# Grab one item; it is still a tensor
my_torch7[7]

tensor(7)

In [22]:
# Grab a slice
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [23]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [24]:
# Keep the original shape, return a column
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

### **Video #4**

In [25]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [26]:
# Addition
tensor_a+tensor_b

tensor([ 6,  8, 10, 12])

In [27]:
# Addition Longhand
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [28]:
# Subtraction
tensor_b-tensor_a

tensor([4, 4, 4, 4])

In [29]:
torch.sub(tensor_b,tensor_a)

tensor([4, 4, 4, 4])

In [30]:
# Multiplication
tensor_a*tensor_b

tensor([ 5, 12, 21, 32])

In [31]:
torch.multiply(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [32]:
tensor_b/tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [35]:
torch.div(tensor_b,tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [36]:
# Remainder Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [39]:
torch.remainder(tensor_b,tensor_a)

tensor([0, 0, 1, 0])

In [40]:
# Exponents / power
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])

In [43]:
# Another way to use the long form
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])