<a href="https://colab.research.google.com/github/dragos000/Pytorch-Tutorial/blob/main/pytorch_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import numpy as np

In [4]:
## Python Lists
my_list = [1,2,3,4]
my_list

[1, 2, 3, 4]

In [6]:
### Numpy Arrays
np1 = np.random.rand(3,4)
np1

array([[0.01820901, 0.22996074, 0.8701962 , 0.73370355],
       [0.4380219 , 0.52297514, 0.05939882, 0.2758449 ],
       [0.55497641, 0.95128582, 0.73873837, 0.68818274]])

In [8]:
np1.dtype

dtype('float64')

In [10]:
## Tensor
tensor_2d = torch.rand(3,4)
tensor_2d

tensor([[0.7404, 0.0478, 0.3121, 0.4906],
        [0.5476, 0.4846, 0.0202, 0.9699],
        [0.7199, 0.1014, 0.8302, 0.6234]])

In [11]:
tensor_2d.dtype

torch.float32

In [12]:
## Create tensor from np array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.0182, 0.2300, 0.8702, 0.7337],
        [0.4380, 0.5230, 0.0594, 0.2758],
        [0.5550, 0.9513, 0.7387, 0.6882]], dtype=torch.float64)